/*********************************************
		外设目录       Device  Index
*********************************************/
#ifndef  __Device_Conf_H_
#define  __Device_Conf_H_

#include "Fdelay.H"
/******************************
LCD12864  三板斧
******************************/
#include "LCD12864_BAISE.H"   //LCD12864  基本通讯
#include "LCD12864_VIEW.H"	  //LCD12864  显示实现
#include "P12864.H"			  //12864界面动画

#include "WORKLED.H"//工作指示灯

#include "EC11.H"  //	EC11旋转编码器

#include "FWLB_Init.H"//外设初始化


#endif

